// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"SimpleLandVehicle","status":true,"description":"v1.2 Allows you to drive/ride a vehicle on land.","parameters":{"Vehicle Speed":"6","Encounters":"false","Touch Events":"true","Action Button Events":"false","Forbid Region ID":"0"}},
{"name":"Hamedo Snippet","status":true,"description":"Hamedo  v.1.00","parameters":{"Multi States":"true","Counter Attack":"22","First Strike":"75","Forestall":"103","Double Strike":"104","Evade and Counter":"74","CounterSameSkill":"106","CounterEvenDeath":"107"}}
];
